onlyBuiltDependencies:
  - '@compodoc/compodoc'
  - '@parcel/watcher'
  - '@swc/core'
  - 'core-js'
  - 'cypress'
  - 'electron'
  - 'electron-winstaller'
  - 'esbuild'
  - 'less'
  - 'lmdb'
  - 'msgpackr-extract'
  - 'nx'
  - 'unrs-resolver'
